name: Eric Semel
favicon: null
layout_spectrum: 0.38539410196244717
typography_spectrum: 0.8011098562274128
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9693969716317952
  lightness: 0.337759705260396
  saturation: 0.9586308321449906
  rhythmicContrast: 0.9784160165581852
purpose: []
